image_width: 640
image_height: 480
camera_name: video2
camera_matrix:
  rows: 3
  cols: 3
  data: [356.47914,  -0.77804, 321.85555,
           0.     , 368.72514, 239.95022,
           0.     ,   0.     ,   1.     ]
distortion_model: equidistant
distortion_coefficients:
  rows: 1
  cols: 4
  data: [0.339231, -1.986036, 6.773656, -4.002578]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [
    509.05229773, 0.0, 333.59489432,0.0,
    0.0, 509.21723083, 240.21732484,0.0,
    0.0, 0.0, 1.00,0.0
    ]
